# Generated by Django 5.2.1 on 2025-05-20 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_check', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.JSONField(blank=True, default=list, help_text="List of attendance records: [{'status': 'present', 'date': 'YYYY-MM-DD', 'time': 'HH:MM:SS'}]")),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_check', to='attendance_check.student')),
            ],
            options={
                'verbose_name_plural': 'Attendance Checks',
            },
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
