# Generated by Django 5.2.1 on 2025-05-20 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_check', '0002_attendancecheck_delete_attendance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttendanceCheck',
            new_name='Attendance',
        ),
    ]
