# Generated by Django 5.2 on 2025-05-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentphoto',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='studentphoto',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
