# Generated by Django 5.2.1 on 2025-05-20 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_studentphoto_thumbnail_and_more'),
        ('attendance_check', '0002_attendancecheck_delete_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentphoto',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='attendance_check.student'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
